const listData: { [key: string]: string[] } = {
    userTypes: [
        'Standard User',
        'Pro',
        'Premium',
        'Business User',
        'Business Admin',
        'Agency User',
        'Agency Admin',
        'Agency Super Admin',
        'System Admin',
        'System Super Admin',
    ],
    recipeCategories: [
        '🩺 Medical',
        '⚖️ Legal',
        '💻 Coding',
        '👶 Kids',
        '🎉 Fun',
        '🖥️ System',
        '🔒 Private',
        '📝 Creative Writing',
        '🧑‍🏫 Homework Help',
        '🧑‍🏫 Tutoring',
        '🔬 Academic Research',
        '📝 Poetry',
        '🏋️ Fitness',
        '🔬 Science',
        '🧮 Math',
        '📉 Statistics',
        '🌐 Language',
        '🧠 Mindfulness',
        '🎤 Motivational Speaking',
        '🏢 Corporate Events',
        '🎊 Weddings',
        '🛠️ IT Troubleshooting',
        '👨‍💻 Software Tutorials',
        '🎥 Movie Recommendations',
        '🧑‍🏫 Education',
        '🎤 Trivia',
        '📈 Data Analysis',
        '🔬 Research Assistance',
        '🌐 Translation',
        '🧠 Mental Health',
        '💸 Financial Advice',
        '🎪 Event Planning',
        '💡 Technical Support',
        '🎟️ Entertainment',
        '🖼️ Art',
        '🖌️ Graphic Design',
        '🎼 Music Composition',
        '📰 News Summarization',
        '🤔 Philosophy',
        '🌿 Environmental Advice',
        '🍳 Cooking',
        '🏋️ Fitness Advice',
        '🏠 Real Estate',
        '💰 Investment Opportunities',
        '👗 Fashion',
        '👔 Style Recommendations',
        '🕹️ Gaming Development',
        '♻️ Sustainability',
        '🥘 Recipe Generation',
        '🏋️ Personal Training',
        '📈 Market Analysis',
        '📈 Marketing',
        '🔍 SEO',
        '📚 Books',
        '🎨 Design',
        '🎬 Movies',
        '🎵 Music',
        '🎮 Games',
        '🍔 Food',
        '🍹 Drinks',
        '🌍 Travel',
        '🚗 Cars',
        '🏡 Home',
        '📦 Shopping',
        '🌸 Aesthetics and Beauty',
    ]

};

export default listData;
